
GET http://localhost:3001/
###

GET http://localhost:3001/api/persons

###
GET http://localhost:3001/info 

###
GET http://localhost:3001/api/persons/2

###
GET http://localhost:3001/api/persons/6
###
DELETE http://localhost:3001/api/persons/-1147667750782072

###
POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "sim",
    "number": "6056789899"
}

###bad post

POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "numer": "6056789899"
}

##unique name

